name: Frontend CI (React Native) with CodeQL
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * 1'  # CodeQL runs every Monday at 12:00 UTC

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  frontend:
    name: Build and Test Frontend (React Native)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install npm Dependencies
        run: |
          npm install
          npm install --save-dev @types/react-native
      - name: Install Expo CLI Globally
        run: npm install -g @expo/cli
      # Uncomment if you have tests and want to run them
      # - name: Run React Native Tests
      #   run: npm test -- --ci --coverage
      #   working-directory: React-native
      - name: Build React Native Project
        run: npx expo export --platform web
        env:
          CI: true # Disable interactive prompts
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: web-build/
          retention-days: 1

  codeql-javascript-analysis:
    name: CodeQL Analysis (JavaScript/TypeScript)
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Dependencies for Analysis
        run: npm install
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"
