name: Deploy to Clever Cloud

on:
  workflow_run:
    workflows: ["Full Stack CI (Java + React Native) "]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLEVER_CLOUD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan push-n3-par-clevercloud-customers.services.clever-cloud.com >> ~/.ssh/known_hosts

      - name: Add Clever Cloud remote
        run: git remote add clever git+ssh://git@push-n3-par-clevercloud-customers.services.clever-cloud.com/app_9b882343-c9f5-40e1-8676-83105ba6e7f2.git

      - name: Push to Clever Cloud
        run: git push --force clever main:master
